server:
  port: 8082
spring:
  cloudinary:
    cloud-name: de01sq6e6
    api-key: 734915739141799
    api-secret: mDBOi1fdfdAbK-LIRaLQ2OLSDZU
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5432/business-helper
    username: postgres
    password: camal123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


  application:
    name: spring-boot-learning
